---

image: "quay.io/repo-runner/alpine-golang"
checkout_dir: /go/src/github.com/repo-runner/repo-runner

commands:
  - make ci

environment:
  CGO_ENABLED: 0
  PACKAGES: github.com/repo-runner/repo-runner/cmd/inner-runner github.com/repo-runner/repo-runner/cmd/repo-runner
